### ISSUE TITLE
Console keyboard not working in Hyper-V Gen2 Windows Server 2019

### ISSUE THREAD

**Issue by mark99i** [kriszos/mikrotikchruefi#1]

**Comment by kriszos** [comment]
Yeah I confirm that, Tho there is nothing that can be done about it within my script. The issue is that MikroTik didn't include necessary drivers for Hyper-V gen2 virtual keyboard. The issue don't exist on KVM/LXD. To remediate it I will add warning in README. Thanks for pointing that out.
